### ISSUE TITLE
Cooperation on an Open-source Brachiation Robot

### ISSUE THREAD

**Issue by Mahdi-Javadi** [xflynx25/BrachiationTrajectoryOptimization#1]
Dear Mr. Flynn, 

My name is Mahdi Javadi, and I am contacting you regarding your exciting work on [Trajectory optimization for brachiation robots with contact](https://github.com/xflynx25/BrachiationTrajectoryOptimization/blob/main/BattleMonkey6832000.pdf). I have already sent ae Email to Prof. Tedrake and Mr. Blake, but I  was not able to find your email address.

We have recently open-sourced the first underactuated brachiator that can perform multiple brachiation maneuvers with passive grippers over a horizontally laid ladder bar. Here you can find the GitHub repository: 
https://github.com/dfki-ric-underactuated-lab/acromonk
and the findings have been submitted to IEEE Robotics and Automation Letters (RA-L) journal. 

We took advantage of pydrake for direct collocation, TVLQR stabilization, and we benchmarked different controllers and behavior generation methods. However, we have not included the contact in trajectory optimization and did not test the brachiation with an inclined ladder bar. 

I was wondering if you are open to cooperation and testing your impressive findings in our AcoMonk system. 

Thank you so much for taking your time and consideration, and I am eagerly awaiting your response. 

Best regards, 
Mahdi Javadi

**Comment by xflynx25** [comment]
Hi Mr. Javadi,

Thanks for reaching out, sorry for my delay I was finishing up a busy semester. I skimmed through your repo and it seems cool what you have done so far, congratulations. The video shows motions similar to those predicted by our simulations. 

I am no longer actively working on this project, although the subject still interests me, so I would consider trying to help out. What did you have in mind in terms of collaboration? 

If you would prefer to take this conversation off-site let me know and I can ask for your email from Prof. Tedrake who you said you have emailed. 

Regards,
xflynx

**Comment by Mahdi-Javadi** [comment]
Dear Mr. Flyn, 
Happy new year and thank you for your response. 
I also prefer to have the conversation off-site. I was not able to find your Email address and this was the intention for opening up the issue here. 

I have sent Prof. Tedrake and Mr.Blake via the Email address: Mahdi.javadi@dfki.de.
It would be very nice of you, when you could close and remove the issue in Github afterwards.

Many thanks and I look forward to hearing from you. 

Best regards, 
Mahdi Javadi
